const icons = [
  { icon: "AiFillTag", title: "Padrão", category: "default" },
  { icon: "FaPizzaSlice", title: "Pizza", category: "food" },
  { icon: "FaHamburger", title: "Hamburger", category: "food" },
  { icon: "IoFastFoodSharp", title: "Hamburger Combo", category: "food" },
  { icon: "FaHotdog", title: "Cachorro Quente", category: "food" },
  { icon: "GiNoodles", title: "Macarrão", category: "food" },
  { icon: "FaBirthdayCake", title: "Bolo", category: "food" },
  { icon: "FaIceCream", title: "Sorvete", category: "food" },
  { icon: "GiSausage", title: "Salsicha", category: "food" },
  { icon: "GiChickenOven", title: "Frango", category: "food" },
  { icon: "GiMeat", title: "Carne", category: "food" },
  { icon: "IoFish", title: "Peixe", category: "food" },
  { icon: "GiCannedFish", title: "Peixe Enlatado", category: "food" },
  { icon: "FaCarrot", title: "Cenoura", category: "food" },
  { icon: "GiBeet", title: "Beterraba", category: "food" },
  { icon: "BsFillEggFill", title: "Ovo", category: "food" },
  { icon: "GiWatermelon", title: "Melancia", category: "food" },
  { icon: "GiBananaBunch", title: "Banana", category: "food" },
  { icon: "GiCorn", title: "Milho", category: "food" },
  { icon: "GiPopcorn", title: "Pipoca", category: "food" },
  { icon: "GiFrenchFries", title: "Batata Frita", category: "food" },
  { icon: "GiBarbecue", title: "Churrasco", category: "food" },
  { icon: "FaCookieBite", title: "Biscoito", category: "food" },
  { icon: "GiCookingPot", title: "Panela", category: "food" },
  { icon: "ImSpoonKnife", title: "Talher", category: "food" },
  { icon: "RiKnifeFill", title: "Faca", category: "food" },
  { icon: "GiCow", title: "Boi", category: "food" },
  { icon: "GiMilkCarton", title: "Leite", category: "food" },
  { icon: "GiJellyBeans", title: "Grãos", category: "food" },
  { icon: "GiBowlOfRice", title: "Prato de Arroz", category: "food" },
  { icon: "GiFruitBowl", title: "Frutas", category: "food" },
  { icon: "GiBubblingBowl", title: "Sopa", category: "food" },
  { icon: "GiShrimp", title: "Frutos do Mar", category: "food" },
  { icon: "GiCheeseWedge", title: "Queijo", category: "food" },
  { icon: "GiSlicedBread", title: "Pão", category: "food" },
  { icon: "GiChipsBag", title: "Arroz, Cuzcuz, Sal", category: "food" },
  { icon: "GiPowderBag", title: "Tempero", category: "food" },
  { icon: "GiDogBowl", title: "Ração", category: "food" },
  { icon: "GiTeapotLeaves", title: "Chá", category: "food" },
  { icon: "GiThreeLeaves", title: "Folhas", category: "food" },
  { icon: "GiPumpkin", title: "Abóbora", category: "food" },
  { icon: "SiBuymeacoffee", title: "Milk Shake", category: "drink" },
  { icon: "IoIosBeer", title: "Bebida", category: "drink" },
  { icon: "GiManualJuicer", title: "Suco", category: "drink" },
  { icon: "GiWaterBottle", title: "Refrigerante", category: "drink" },
  { icon: "GiWineBottle", title: "Vinho", category: "drink" },
  { icon: "GiWaterFlask", title: "Água", category: "drink" },
  { icon: "MdCleanHands", title: "Produtos de Limpeza", category: "cleaner" },
  { icon: "GiShower", title: "Banho", category: "cleaner" },
  { icon: "FaPumpSoap", title: "Sabonete Líquido", category: "cleaner" },
  { icon: "FaPumpMedical", title: "Limpeza e Saúde", category: "cleaner" },
  { icon: "GiVacuumCleaner", title: "Aspirador de Pó", category: "cleaner" },
  { icon: "GiWashingMachine", title: "Máquina de Lavar", category: "cleaner" },
  { icon: "MdDryCleaning", title: "Cabides", category: "utilities" },
  { icon: "GiBroom", title: "Vassoura", category: "utilities" },
  { icon: "GiMedicinePills", title: "Remédio", category: "health" },
  { icon: "GiMedicines", title: "Remédio Pílulas", category: "health" },
  { icon: "GiBabyBottle", title: "Mamadeira", category: "health" },
  { icon: "FaBaby", title: "Produtos para Bebê", category: "health" },
  { icon: "FaDog", title: "Pet Shop", category: "health" },
  { icon: "FaTshirt", title: "Camiseta", category: "clothing" },
  { icon: "RiShirtFill", title: "Camiseta Social", category: "clothing" },
  { icon: "GiPoloShirt", title: "Camiseta Polo", category: "clothing" },
  { icon: "GiUnderwearShorts", title: "Cuecas", category: "clothing" },
  { icon: "GiUnderwear", title: "Calcinhas", category: "clothing" },
  { icon: "GiArmoredPants", title: "Calça", category: "clothing" },
  { icon: "GiLargeDress", title: "Vestido", category: "clothing" },
  { icon: "GiSkirt", title: "Saia", category: "clothing" },
  { icon: "GiShorts", title: "Bermudas", category: "clothing" },
  { icon: "GiRunningShoe", title: "Sapato", category: "shoe" },
  { icon: "GiSonicShoes", title: "Sandália", category: "shoe" },
  { icon: "GiWoodenClogs", title: "Tamanco", category: "shoe" },
  { icon: "GiSteeltoeBoots", title: "Bota", category: "shoe" },
  { icon: "GiDelicatePerfume", title: "Perfume", category: "accessories" },
  { icon: "GiDropEarrings", title: "Brincos e Jóias", category: "accessories" },
  { icon: "BsFillHandbagFill", title: "Bolsa", category: "accessories" },
  { icon: "BsSunglasses", title: "Óculos", category: "accessories" },
  { icon: "GiBelt", title: "Cinto", category: "accessories" },
];

export { icons };
