const icons = [
  { icon: "FaPizzaSlice", title: "Pizza", category: "food" },
  { icon: "FaHamburger", title: "Hamburger", category: "food" },
  { icon: "IoFastFoodSharp", title: "Hamburger Combo", category: "food" },
  { icon: "FaHotdog", title: "Cachorro Quente", category: "food" },
  { icon: "GiNoodles", title: "Macarrão", category: "food" },
  { icon: "FaBirthdayCake", title: "Bolo", category: "food" },
  { icon: "FaIceCream", title: "Sorvete", category: "food" },
  { icon: "GiSausage", title: "Salsicha", category: "food" },
  { icon: "GiChickenOven", title: "Frango", category: "food" },
  { icon: "GiMeat", title: "Carne", category: "food" },
  { icon: "IoFish", title: "Peixe", category: "food" },
  { icon: "GiCannedFish", title: "Peixe Enlatado", category: "food" },
  { icon: "FaCarrot", title: "Cenoura", category: "food" },
  { icon: "GiBeet", title: "Beterraba", category: "food" },
  { icon: "BsFillEggFill", title: "Ovo", category: "food" },
  { icon: "GiWatermelon", title: "Melancia", category: "food" },
  { icon: "GiBananaBunch", title: "Banana", category: "food" },
  { icon: "GiCorn", title: "Milho", category: "food" },
  { icon: "GiPopcorn", title: "Pipoca", category: "food" },
  { icon: "GiFrenchFries", title: "Batata Frita", category: "food" },
  { icon: "GiBarbecue", title: "Churrasco", category: "food" },
  { icon: "FaCookieBite", title: "Biscoito", category: "food" },
  { icon: "GiCookingPot", title: "Panela", category: "food" },
  { icon: "ImSpoonKnife", title: "Talher", category: "food" },
  { icon: "RiKnifeFill", title: "Faca", category: "food" },
  { icon: "GiCow", title: "Boi", category: "food" },
  { icon: "GiMilkCarton", title: "Leite", category: "food" },
  { icon: "GiJellyBeans", title: "Grãos", category: "food" },
  { icon: "GiBowlOfRice", title: "Prato de Arroz", category: "food" },
  { icon: "GiFruitBowl", title: "Frutas", category: "food" },
  { icon: "GiBubblingBowl", title: "Sopa", category: "food" },
  { icon: "GiShrimp", title: "Frutos do Mar", category: "food" },
  { icon: "IoIosBeer", title: "Bebida", category: "drink" },
  { icon: "GiManualJuicer", title: "Suco", category: "drink" },
  { icon: "GiWaterBottle", title: "Refrigerante", category: "drink" },
  { icon: "GiWineBottle", title: "Vinho", category: "drink" },
  { icon: "GiWaterFlask", title: "Água", category: "drink" },
  { icon: "MdCleanHands", title: "Produtos de Limpeza", category: "cleaner" },
  { icon: "GiShower", title: "Banho", category: "cleaner" },
];

export { icons };
